name: hyperion-ng
base: core22
adopt-info: hyperion-ng

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run on: amd64
  - build-on: amd64
    run on: arm64

apps:
  hyperion-ng:
    command: usr/local/bin/hyperiond
    plugs:
      - camera
      - framebuffer
      - hidraw
      - home
      - network-control
      - network-status
      - network-bind
      - network
      - raw-usb
      - serial-port
      - tpm
      - unity7
      - x11
    common-id: com.hyperion-project.hyperion
    desktop: usr/local/share/hyperion/desktop/hyperion.desktop

parts:
  hyperion-ng:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DUSE_SYSTEM_MBEDTLS_LIBS=ON
      - -DUSE_SYSTEM_FLATBUFFERS_LIBS=ON
      - -DUSE_SYSTEM_PROTO_LIBS=ON
      - -DENABLE_DEPLOY_DEPENDENCIES=OFF
    cmake-generator: Ninja
    source-type: git
    source: https://github.com/hyperion-project/hyperion.ng
    source-branch: master
    parse-info: [usr/local/share/hyperion/desktop/hyperion.metainfo.xml]
    build-packages:
      - git
      - cmake
      - build-essential
      - qt6-base-dev
      - libqt6serialport6-dev
      - libqt6sql6-sqlite
      - libxkbcommon-dev
      - libvulkan-dev
      - libgl1-mesa-dev
      - python3-dev
      - libusb-1.0-0-dev
      - libcec-dev
      - libp8-platform-dev
      - libudev-dev
      - libavahi-core-dev
      - libavahi-compat-libdnssd-dev
      - zlib1g-dev
      - libasound2-dev
      - libjpeg-dev
      - libturbojpeg0-dev
      - libmbedtls-dev
      - libflatbuffers-dev
      - flatbuffers-compiler
      - libprotobuf-dev
      - protobuf-compiler
      - libftdi1-dev
      - libssl-dev
      - libglib2.0-dev
      - libxrandr-dev
      - libxrender-dev
      - libxcb-image0-dev
      - libxcb-util0-dev
      - libxcb-shm0-dev
      - libxcb-render0-dev
      - libxcb-randr0-dev
    stage-packages:
      - libqt6network6
      - libqt6widgets6
      - libqt6sql6
      - libqt6serialport6
      - libqt6sql6-sqlite
      - libpython3.10
      - libusb-1.0-0
      - libasound2
      - libmbedtls14
      - libflatbuffers1
      - libprotobuf23
      - libturbojpeg
      - libcec6
      - libxcb-render-util0
    override-pull: |
      craftctl default
      craftctl set version=$(cat .version)
      # Update the icon path
      sed -i 's|Icon=hyperion|Icon=usr/local/share/hyperion/icons/256x256/apps/hyperion\.png|' cmake/desktop/hyperion.desktop
