name: hyperion-ng
adopt-info: hyperion-ng

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

environment:
  QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins"

apps:
  hyperion-ng:
    extensions: [gnome]
    command: usr/local/bin/hyperiond
    common-id: com.hyperion-project.hyperion
    desktop: usr/local/share/hyperion/desktop/hyperion.desktop
    plugs:
      - camera
      - framebuffer
      - hidraw
      - home
      - network-control
      - network-status
      - network-bind
      - network
      - raw-usb
      - serial-port
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7

parts:
  hyperion-ng:
    plugin: cmake
    source-type: git
    source-branch: master
    source: https://github.com/hyperion-project/hyperion.ng
    parse-info: [usr/local/share/hyperion/desktop/hyperion.metainfo.xml]
    build-packages:
      - git
      - cmake
      - build-essential
      - qt6-base-dev
      - libqt6serialport6-dev
      - libqt6sql6-sqlite
      - libxkbcommon-dev
      - libvulkan-dev
      - libgl1-mesa-dev
      - python3-dev
      - libusb-1.0-0-dev
      - libcec-dev
      - libp8-platform-dev
      - libudev-dev
      - libavahi-core-dev
      - libavahi-compat-libdnssd-dev
      - zlib1g-dev
      - libasound2-dev
      - libjpeg-dev
      - libturbojpeg0-dev
      - libmbedtls-dev
      - libflatbuffers-dev
      - flatbuffers-compiler
      - libprotobuf-dev
      - protobuf-compiler
      - libftdi1-dev
      - libssl-dev
      - libglib2.0-dev
      - libxrandr-dev
      - libxrender-dev
      - libxcb-image0-dev
      - libxcb-util0-dev
      - libxcb-shm0-dev
      - libxcb-render0-dev
      - libxcb-randr0-dev
    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6network6
      - libqt6widgets6
      - libqt6sql6
      - libqt6serialport6
      - libqt6sql6-sqlite
      - qt6-gtk-platformtheme
      - qt6-qpa-plugins
      - qt6-wayland
      - libpython3.10
      - libusb-1.0-0
      - libasound2
      - libmbedtls14
      - libflatbuffers1
      - libprotobuf23
      - libturbojpeg
      - libcec6
      - libxcb-render-util0
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DUSE_SYSTEM_MBEDTLS_LIBS=ON
      - -DUSE_SYSTEM_FLATBUFFERS_LIBS=ON
      - -DUSE_SYSTEM_PROTO_LIBS=ON
      - -DENABLE_DEPLOY_DEPENDENCIES=OFF
    override-pull: |
      craftctl default
      craftctl set version=$(cat .version)
      mkdir -p "${CRAFT_PART_INSTALL}/usr/local/share/hyperion/desktop"
      cp "${CRAFT_PART_SRC}/resources/icons/hyperion-256px.png" "${CRAFT_PART_INSTALL}/usr/local/share/hyperion/desktop/hyperion.png"
      sed -i 's|Icon=hyperion|Icon=usr/local/share/hyperion/desktop/hyperion\.png|' ${CRAFT_PART_SRC}/cmake/desktop/hyperion.desktop
    override-build: |
      craftctl default
      rm -rf "$CRAFT_PART_INSTALL/usr/local/share/hyperion/service" "$CRAFT_PART_INSTALL/usr/local/share/hyperion/icons" "$CRAFT_PART_INSTALL/usr/local/share/hyperion/scripts"
    stage:
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libEGL_mesa*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libGLX_mesa*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libcec*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libcolordprivate*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libdconf*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libflatbuffers*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libicuio*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libicutest*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libdebug_sym*
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libdtovl*

  # This part removes all the files in this snap which already exist in connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be included in this snap itself.
  # More info: https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280#heading--cleanup-part
  cleanup:
    after:
      - hyperion-ng
    plugin: nil
    build-snaps:
      - core22
      - gnome-42-2204
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes" ; do 
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done