name: hyperion-ng
adopt-info: hyperion-ng

base: core24
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  armhf:

apps:
  hyperion-ng:
    extensions: [gnome]
    command: usr/local/bin/hyperiond
    common-id: com.hyperion-project.hyperion
    desktop: usr/share/applications/com.hyperion-project.hyperion.desktop
    plugs:
      - camera
      - framebuffer
      - hidraw
      - home
      - network-control
      - network-status
      - network-bind
      - network
      - raw-usb
      - serial-port
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins

parts:
  hyperion-ng:
    source: https://github.com/hyperion-project/hyperion.ng
    source-type: git
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DUSE_SYSTEM_MBEDTLS_LIBS=ON
      - -DUSE_SYSTEM_FLATBUFFERS_LIBS=ON
      - -DUSE_SYSTEM_PROTO_LIBS=ON
      - -DENABLE_DEPLOY_DEPENDENCIES=OFF
    parse-info:
      - usr/share/metainfo/com.hyperion-project.hyperion.metainfo.xml
    build-packages:
      - git
      - cmake
      - build-essential
      - ninja-build
      - qt6-base-dev
      - libqt6serialport6-dev
      - libqt6sql6-sqlite
      - libqt6websockets6-dev
      - libxkbcommon-dev
      - libvulkan-dev
      - libgl1-mesa-dev
      - python3-dev
      - libusb-1.0-0-dev
      - libcec-dev
      - libp8-platform-dev
      - libudev-dev
      - libavahi-core-dev
      - libavahi-compat-libdnssd-dev
      - zlib1g-dev
      - libasound2-dev
      - libjpeg-dev
      - libturbojpeg0-dev
      - libmbedtls-dev
      - libflatbuffers-dev
      - flatbuffers-compiler
      - flatbuffers
      - libprotobuf-dev
      - protobuf-compiler
      - libftdi1-dev
      - libssl-dev
      - libglib2.0-dev
      - libxrandr-dev
      - libxrender-dev
      - libxcb-image0-dev
      - libxcb-util0-dev
      - libxcb-shm0-dev
      - libxcb-render0-dev
      - libxcb-randr0-dev
    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6network6
      - libqt6widgets6
      - libqt6sql6
      - libqt6serialport6
      - libqt6sql6-sqlite
      - libqt6websockets6
      - qt6-gtk-platformtheme
      - qt6-qpa-plugins
      - qt6-wayland
      - libpython3.12
      - libusb-1.0-0
      - libasound2
      - libmbedtls14
      - libprotobuf32t64
      - libturbojpeg
      - libcec6
    override-pull: |
      craftctl default
      craftctl set version=$(cat .version)
      mkdir -p ${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/256x256/apps
      cp ${CRAFT_PART_SRC}/resources/icons/hyperion-256px.png ${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/256x256/apps/com.hyperion-project.hyperion.png
      mkdir -p ${CRAFT_PART_INSTALL}/usr/share/applications
      cp ${CRAFT_PART_SRC}/cmake/linux/desktop/hyperion.desktop ${CRAFT_PART_INSTALL}/usr/share/applications/com.hyperion-project.hyperion.desktop
      sed -i 's|Icon=hyperion|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/com.hyperion-project.hyperion.png|' ${CRAFT_PART_INSTALL}/usr/share/applications/com.hyperion-project.hyperion.desktop
      mkdir -p ${CRAFT_PART_INSTALL}/usr/share/metainfo
      cp ${CRAFT_PART_SRC}/cmake/linux/desktop/hyperion.metainfo.xml ${CRAFT_PART_INSTALL}/usr/share/metainfo/com.hyperion-project.hyperion.metainfo.xml
    stage:
      - -usr/local/share/hyperion/service
      - -usr/local/share/hyperion/icons
      - -usr/local/share/hyperion/desktop
      - -usr/local/share/hyperion/scripts

  # This part removes all the files in this snap which already exist in connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be included in this snap itself.
  # More info: https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280#heading--cleanup-part
  cleanup:
    after:
      - hyperion-ng
    plugin: nil
    build-snaps:
      - core22
      - gnome-42-2204
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes" ; do 
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done