name: Build Snap

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.target_platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        target_platform:
        - amd64
        - armhf
        - arm64
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Build
      id: build
      uses: diddlesnaps/snapcraft-multiarch-action@v1
      with:
        architecture: ${{ matrix.target_platform }}