name: Build Snap

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.architecture == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    strategy:
      fail-fast: false
      matrix:
        architecture:
        - amd64
        - arm64
        - armhf

    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Build
      id: snapcraft
      uses: snapcore/action-build@v1

    - name: Show logs if failed
      if: failure()
      run: cat ~/.local/state/snapcraft/log/*.log